### ISSUE TITLE
Depot does not find globally installed pnpm

### ISSUE THREAD

**Issue by djsavvy** [cognitive-engineering-lab/depot#42]
I'm using depot to try and build https://github.com/nota-lang/bene locally, and am following the instructions in that README (essentially cloning, and then running `depot -p bene-web build`). 

This was failing with the following output, despite me having `pnpm` installed globally via Homebrew: 

```
Depot failed with the error:

Executable is missing: /Users/savvy/.local/bin/pnpm
```

I was able to fix this by running `ln -s $(which pnpm) ~/.local/bin/pnpm`, but this shouldn't really be necessary IMO. Depot should be able to find the globally installed `pnpm` and use that instead of looking for it in a specific place.

**Comment by willcrichton** [comment]
So what should happen is the install script runs `depot setup`, and that should download a specific version of pnpm to `~/.local/bin`. It seems like `depot setup` did not run or did not work (did you use the depot install script?). I realize `depot setup` is not documented for the from-source instructions, so I will add that.

**Comment by willcrichton** [comment]
(I can, nonetheless, add a fall-back search for global pnpm if depot's does not exist.)

**Comment by taladar** [comment]
If neither is installed it just seems to produce the unhelpful error message, that should probably be fixed too.

```
Depot failed with the error:

No such file or directory (os error 2)
```
