### ISSUE TITLE
depot doc does not work in newly generated library project in workspace

### ISSUE THREAD

**Issue by taladar** [cognitive-engineering-lab/depot#45]
I basically did

```
cargo install depot-js --locked
depot setup
depot new --workspace depot-workspace
cd depot-workspace
depot new --target site --platform browser depot-test
depot new --target lib --platform browser depot-test-lib
```

to generate a project structure to test depot for the first time today.

I then tried the various commands and (from what I can tell at a casual glance) they all seem to be working as expected but 

```
depot doc
```
prints
```
ws/typedoc
│ [warning] The 'typedoc' key in ./packages/depot-test-lib/package.json was used by the legacy-packages entryPointStrategy and will be ignored.
│ [info] Converting project at ./packages/depot-test-lib
│ [warning] No entry points were provided, this is likely a misconfiguration.
│ [info] Merging converted projects
│ [info] Documentation generated at ./docs
└─ finished
```

and the resulting documentation does not seem to include the add function that is generated as an example or really much of anything other than the package name as a module.

**Comment by willcrichton** [comment]
Ah, it seems that Typedoc changed their configuration strategy to use `tsconfig.json` instead of `package.json`. I'll update Depot to match, thanks.
